FROM golang:1.27-alpine AS build

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /mockrpc ./cmd/mockrpc

FROM alpine:3.24
COPY --from=build /mockrpc /mockrpc
EXPOSE 8081
ENTRYPOINT ["/mockrpc"]
