// Code generated by cmd/clientgen from api/openapi.yaml; DO NOT EDIT.
//
// The generated surface (types, per-operation methods, SpecRoutes and
// SpecVersion) is verified against api/openapi.yaml by
// pkg/client/drift_test.go. Regenerate with `make client` after
// changing the spec.
package client

import (
	"context"
	"net/url"
	"strconv"
)

// SpecVersion is the api/openapi.yaml info.version this client was
// generated from. A client built against a different spec version may
// not be wire-compatible with a running server.
const SpecVersion = "0.1.0"

// SpecRoute is one (method, path) pair documented in the spec.
type SpecRoute struct {
	Method string
	Path   string
}

// SpecRoutes lists every (method, path) pair in api/openapi.yaml at
// generation time. pkg/client/drift_test.go compares it against the live
// spec so the client can never silently drift from the documented API.
var SpecRoutes = []SpecRoute{
	{Method: "GET", Path: "/addresses/{address}/events"},
	{Method: "GET", Path: "/addresses/{address}/summary"},
	{Method: "DELETE", Path: "/admin/keys/{key_id}"},
	{Method: "GET", Path: "/admin/tenants"},
	{Method: "POST", Path: "/admin/tenants"},
	{Method: "DELETE", Path: "/admin/tenants/{id}"},
	{Method: "GET", Path: "/admin/tenants/{id}"},
	{Method: "PATCH", Path: "/admin/tenants/{id}"},
	{Method: "GET", Path: "/admin/tenants/{id}/grants"},
	{Method: "POST", Path: "/admin/tenants/{id}/grants"},
	{Method: "DELETE", Path: "/admin/tenants/{id}/grants/{contract_id}"},
	{Method: "GET", Path: "/admin/tenants/{id}/keys"},
	{Method: "POST", Path: "/admin/tenants/{id}/keys"},
	{Method: "GET", Path: "/admin/tenants/{id}/usage"},
	{Method: "GET", Path: "/contracts"},
	{Method: "GET", Path: "/contracts/{id}"},
	{Method: "GET", Path: "/contracts/{id}/events"},
	{Method: "GET", Path: "/contracts/{id}/export"},
	{Method: "GET", Path: "/contracts/{id}/stats"},
	{Method: "GET", Path: "/dead-letters"},
	{Method: "DELETE", Path: "/dead-letters/{id}"},
	{Method: "DELETE", Path: "/events"},
	{Method: "GET", Path: "/events"},
	{Method: "GET", Path: "/events.csv"},
	{Method: "GET", Path: "/events/aggregate"},
	{Method: "GET", Path: "/events/count"},
	{Method: "GET", Path: "/events/ws"},
	{Method: "GET", Path: "/events/{id}"},
	{Method: "GET", Path: "/events/{id}/raw"},
	{Method: "GET", Path: "/events/{id}/transaction"},
	{Method: "GET", Path: "/health"},
	{Method: "GET", Path: "/livez"},
	{Method: "GET", Path: "/metrics"},
	{Method: "GET", Path: "/readyz"},
	{Method: "GET", Path: "/stats"},
	{Method: "GET", Path: "/subscriptions"},
	{Method: "POST", Path: "/subscriptions"},
	{Method: "DELETE", Path: "/subscriptions/{id}"},
	{Method: "GET", Path: "/subscriptions/{id}"},
	{Method: "PUT", Path: "/subscriptions/{id}"},
	{Method: "GET", Path: "/subscriptions/{id}/deliveries"},
	{Method: "GET", Path: "/tenant"},
	{Method: "GET", Path: "/tenant/usage"},
	{Method: "GET", Path: "/tenant/watch"},
	{Method: "POST", Path: "/tenant/watch"},
	{Method: "DELETE", Path: "/tenant/watch/{contract_id}"},
	{Method: "GET", Path: "/version"},
	{Method: "GET", Path: "/watched-contracts"},
	{Method: "POST", Path: "/watched-contracts"},
	{Method: "DELETE", Path: "/watched-contracts/{id}"},
}

type ContractSummary struct {
	ContractID  string `json:"contract_id"`
	EventCount  int64  `json:"event_count"`
	FirstLedger int64  `json:"first_ledger"`
	LastLedger  int64  `json:"last_ledger"`
	LastSeen    string `json:"last_seen"`
}

type ContractsPage struct {
	Contracts []ContractSummary `json:"contracts"`
	Count     int64             `json:"count"`
	Cursor    string            `json:"cursor,omitempty"`
}

type CreateSubscriptionRequest struct {
	Enabled bool               `json:"enabled,omitempty"`
	Filters SubscriptionFilter `json:"filters,omitempty"`
	Secret  string             `json:"secret"`
	Url     string             `json:"url"`
}

type DeliveryAttempt struct {
	CreatedAt      string `json:"created_at"`
	DurationMs     int64  `json:"duration_ms"`
	Error          string `json:"error,omitempty"`
	EventID        string `json:"event_id"`
	ID             int64  `json:"id"`
	ResponseCode   int64  `json:"response_code"`
	Status         string `json:"status"`
	SubscriptionID int64  `json:"subscription_id"`
}

type EnrichedEvent map[string]any

type ErrorResponse struct {
	Error string `json:"error"`
}

type Event struct {
	ContractID       string `json:"contract_id"`
	CreatedAt        string `json:"created_at"`
	ID               string `json:"id"`
	InSuccessfulCall bool   `json:"in_successful_call"`
	Ledger           int64  `json:"ledger"`
	OpIndex          int64  `json:"op_index"`
	Topics           []any  `json:"topics"`
	TxHash           string `json:"tx_hash"`
	TxIndex          int64  `json:"tx_index"`
	Type             string `json:"type"`
	Value            any    `json:"value"`
}

type EventsResponse struct {
	Cursor string  `json:"cursor,omitempty"`
	Events []Event `json:"events"`
}

type HealthResponse struct {
	Checks map[string]any `json:"checks"`
	Status string         `json:"status"`
}

type Stats struct {
	Auditor *struct {
		FindingsOpened        int64 `json:"findings_opened,omitempty"`
		FindingsRepaired      int64 `json:"findings_repaired,omitempty"`
		FindingsUnrecoverable int64 `json:"findings_unrecoverable,omitempty"`
		FindingsUnverifiable  int64 `json:"findings_unverifiable,omitempty"`
		LedgersChecked        int64 `json:"ledgers_checked,omitempty"`
		PassesRun             int64 `json:"passes_run,omitempty"`
		RpcRequests           int64 `json:"rpc_requests,omitempty"`
	} `json:"auditor,omitempty"`
	ContractCount         int64 `json:"contract_count,omitempty"`
	LastIngestedLedger    int64 `json:"last_ingested_ledger,omitempty"`
	TotalEvents           int64 `json:"total_events,omitempty"`
	VerifiedThroughLedger int64 `json:"verified_through_ledger,omitempty"`
	WatchedContracts      int64 `json:"watched_contracts,omitempty"`
}

type Subscription struct {
	CreatedAt    string             `json:"created_at"`
	Enabled      bool               `json:"enabled"`
	FailureCount int64              `json:"failure_count"`
	Filters      SubscriptionFilter `json:"filters"`
	ID           int64              `json:"id"`
	Secret       string             `json:"secret"`
	Url          string             `json:"url"`
}

type SubscriptionFilter struct {
	ContractID string `json:"contract_id,omitempty"`
	FromLedger int64  `json:"from_ledger,omitempty"`
	ToLedger   int64  `json:"to_ledger,omitempty"`
	Topic      any    `json:"topic,omitempty"`
	Type       string `json:"type,omitempty"`
}

type UpdateSubscriptionRequest struct {
	Enabled bool               `json:"enabled,omitempty"`
	Filters SubscriptionFilter `json:"filters,omitempty"`
	Secret  string             `json:"secret,omitempty"`
	Url     string             `json:"url,omitempty"`
}

type AddTenantWatchResponse map[string]any

type AddWatchedContractResponse map[string]any

type AddressSummaryResponse map[string]any

type AggregateEventsResponse struct {
	Buckets []struct {
		Count int64  `json:"count,omitempty"`
		Key   string `json:"key,omitempty"`
	} `json:"buckets,omitempty"`
}

type ContractStatsResponse struct {
	ContractID    string `json:"contract_id"`
	Decimals      int64  `json:"decimals,omitempty"`
	EventCount    int64  `json:"event_count"`
	Name          string `json:"name,omitempty"`
	Symbol        string `json:"symbol,omitempty"`
	TypeBreakdown []struct {
		Count int64  `json:"count"`
		Type  string `json:"type"`
	} `json:"type_breakdown,omitempty"`
}

type CountEventsResponse struct {
	Count int64 `json:"count,omitempty"`
}

type CreateTenantKeyResponse map[string]any

type CreateTenantResponse map[string]any

type CurrentTenantResponse map[string]any

type CurrentTenantUsageResponse map[string]any

type DeleteEventsResponse struct {
	Deleted int64 `json:"deleted,omitempty"`
}

type GetContractResponse struct {
	ContractID  string `json:"contract_id"`
	EventCount  int64  `json:"event_count"`
	FirstLedger int64  `json:"first_ledger"`
	LastLedger  int64  `json:"last_ledger"`
	LastSeen    string `json:"last_seen"`
}

type GetEventResponse = Event

type GetTenantResponse map[string]any

type GrantContractResponse map[string]any

type ListDeadLettersResponse map[string]any

type ListTenantGrantsResponse map[string]any

type ListTenantKeysResponse map[string]any

type ListTenantsResponse map[string]any

type ListWatchedContractsResponse map[string]any

type RawEventResponse struct {
	TopicsXdr []string `json:"topics_xdr,omitempty"`
	ValueXdr  string   `json:"value_xdr,omitempty"`
}

type RemoveTenantWatchResponse map[string]any

type RemoveWatchedContractResponse map[string]any

type RevokeContractResponse map[string]any

type TenantUsageResponse map[string]any

type TenantWatchListResponse map[string]any

type UpdateTenantResponse map[string]any

type VersionResponse struct {
	BuildDate string `json:"build_date,omitempty"`
	Commit    string `json:"commit,omitempty"`
	Version   string `json:"version,omitempty"`
}

// AddressEvents List events involving an address.
//
// GET /addresses/{address}/events
func (c *Client) AddressEvents(ctx context.Context, address string, params AddressEventsParams) (*EventsResponse, error) {
	path := urlEscapePath("/addresses/{address}/events", address)
	query := params.values()
	return do[EventsResponse](c, ctx, "GET", path, query, nil)
}

// AddressEventsParams are the query parameters for AddressEvents.
type AddressEventsParams struct {
	FromLedger int64
	ToLedger   int64
	Limit      int64
	Cursor     string
	Order      string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p AddressEventsParams) values() url.Values {
	v := url.Values{}
	if p.FromLedger != 0 {
		v.Set("from_ledger", strconv.FormatInt(p.FromLedger, 10))
	}
	if p.ToLedger != 0 {
		v.Set("to_ledger", strconv.FormatInt(p.ToLedger, 10))
	}
	if p.Limit != 0 {
		v.Set("limit", strconv.FormatInt(p.Limit, 10))
	}
	if p.Cursor != "" {
		v.Set("cursor", p.Cursor)
	}
	if p.Order != "" {
		v.Set("order", p.Order)
	}
	return v
}

// AddressSummary Summarise an address's event history.
//
// GET /addresses/{address}/summary
func (c *Client) AddressSummary(ctx context.Context, address string) (*AddressSummaryResponse, error) {
	path := urlEscapePath("/addresses/{address}/summary", address)
	return do[AddressSummaryResponse](c, ctx, "GET", path, nil, nil)
}

// RevokeKey Revoke an API key.
//
// DELETE /admin/keys/{key_id}
func (c *Client) RevokeKey(ctx context.Context, keyID int64) error {
	path := urlEscapePath("/admin/keys/{key_id}", strconv.FormatInt(keyID, 10))
	return doNoContent(c, ctx, "DELETE", path, nil, nil)
}

// ListTenants List tenants.
//
// GET /admin/tenants
func (c *Client) ListTenants(ctx context.Context) (*ListTenantsResponse, error) {
	path := "/admin/tenants"
	return do[ListTenantsResponse](c, ctx, "GET", path, nil, nil)
}

// CreateTenant Create a tenant.
//
// POST /admin/tenants
func (c *Client) CreateTenant(ctx context.Context) (*CreateTenantResponse, error) {
	path := "/admin/tenants"
	return do[CreateTenantResponse](c, ctx, "POST", path, nil, nil)
}

// DeleteTenant Delete a tenant.
//
// DELETE /admin/tenants/{id}
func (c *Client) DeleteTenant(ctx context.Context, id int64) error {
	path := urlEscapePath("/admin/tenants/{id}", strconv.FormatInt(id, 10))
	return doNoContent(c, ctx, "DELETE", path, nil, nil)
}

// GetTenant Get a tenant.
//
// GET /admin/tenants/{id}
func (c *Client) GetTenant(ctx context.Context, id int64) (*GetTenantResponse, error) {
	path := urlEscapePath("/admin/tenants/{id}", strconv.FormatInt(id, 10))
	return do[GetTenantResponse](c, ctx, "GET", path, nil, nil)
}

// UpdateTenant Update a tenant.
//
// PATCH /admin/tenants/{id}
func (c *Client) UpdateTenant(ctx context.Context, id int64) (*UpdateTenantResponse, error) {
	path := urlEscapePath("/admin/tenants/{id}", strconv.FormatInt(id, 10))
	return do[UpdateTenantResponse](c, ctx, "PATCH", path, nil, nil)
}

// ListTenantGrants List a tenant's contract grants.
//
// GET /admin/tenants/{id}/grants
func (c *Client) ListTenantGrants(ctx context.Context, id int64) (*ListTenantGrantsResponse, error) {
	path := urlEscapePath("/admin/tenants/{id}/grants", strconv.FormatInt(id, 10))
	return do[ListTenantGrantsResponse](c, ctx, "GET", path, nil, nil)
}

// GrantContract Grant a contract to a tenant.
//
// POST /admin/tenants/{id}/grants
func (c *Client) GrantContract(ctx context.Context, id int64) (*GrantContractResponse, error) {
	path := urlEscapePath("/admin/tenants/{id}/grants", strconv.FormatInt(id, 10))
	return do[GrantContractResponse](c, ctx, "POST", path, nil, nil)
}

// RevokeContract Revoke a contract grant.
//
// DELETE /admin/tenants/{id}/grants/{contract_id}
func (c *Client) RevokeContract(ctx context.Context, id int64, contractID string) (*RevokeContractResponse, error) {
	path := urlEscapePath("/admin/tenants/{id}/grants/{contract_id}", strconv.FormatInt(id, 10), contractID)
	return do[RevokeContractResponse](c, ctx, "DELETE", path, nil, nil)
}

// ListTenantKeys List a tenant's API keys.
//
// GET /admin/tenants/{id}/keys
func (c *Client) ListTenantKeys(ctx context.Context, id int64) (*ListTenantKeysResponse, error) {
	path := urlEscapePath("/admin/tenants/{id}/keys", strconv.FormatInt(id, 10))
	return do[ListTenantKeysResponse](c, ctx, "GET", path, nil, nil)
}

// CreateTenantKey Issue an API key for a tenant.
//
// POST /admin/tenants/{id}/keys
func (c *Client) CreateTenantKey(ctx context.Context, id int64) (*CreateTenantKeyResponse, error) {
	path := urlEscapePath("/admin/tenants/{id}/keys", strconv.FormatInt(id, 10))
	return do[CreateTenantKeyResponse](c, ctx, "POST", path, nil, nil)
}

// TenantUsage Get a tenant's recorded usage.
//
// GET /admin/tenants/{id}/usage
func (c *Client) TenantUsage(ctx context.Context, id int64, params TenantUsageParams) (*TenantUsageResponse, error) {
	path := urlEscapePath("/admin/tenants/{id}/usage", strconv.FormatInt(id, 10))
	query := params.values()
	return do[TenantUsageResponse](c, ctx, "GET", path, query, nil)
}

// TenantUsageParams are the query parameters for TenantUsage.
type TenantUsageParams struct {
	Days int64
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p TenantUsageParams) values() url.Values {
	v := url.Values{}
	if p.Days != 0 {
		v.Set("days", strconv.FormatInt(p.Days, 10))
	}
	return v
}

// ListContracts List indexed contracts.
//
// GET /contracts
func (c *Client) ListContracts(ctx context.Context, params ListContractsParams) (*ContractsPage, error) {
	path := "/contracts"
	query := params.values()
	return do[ContractsPage](c, ctx, "GET", path, query, nil)
}

// ListContractsParams are the query parameters for ListContracts.
type ListContractsParams struct {
	Limit      int64
	Cursor     string
	Sort       string
	Order      string
	ContractID string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p ListContractsParams) values() url.Values {
	v := url.Values{}
	if p.Limit != 0 {
		v.Set("limit", strconv.FormatInt(p.Limit, 10))
	}
	if p.Cursor != "" {
		v.Set("cursor", p.Cursor)
	}
	if p.Sort != "" {
		v.Set("sort", p.Sort)
	}
	if p.Order != "" {
		v.Set("order", p.Order)
	}
	if p.ContractID != "" {
		v.Set("contract_id", p.ContractID)
	}
	return v
}

// GetContract Get a single contract's summary.
//
// GET /contracts/{id}
func (c *Client) GetContract(ctx context.Context, id string) (*GetContractResponse, error) {
	path := urlEscapePath("/contracts/{id}", id)
	return do[GetContractResponse](c, ctx, "GET", path, nil, nil)
}

// ContractEvents List events for a contract.
//
// GET /contracts/{id}/events
func (c *Client) ContractEvents(ctx context.Context, id string, params ContractEventsParams) (*EventsResponse, error) {
	path := urlEscapePath("/contracts/{id}/events", id)
	query := params.values()
	return do[EventsResponse](c, ctx, "GET", path, query, nil)
}

// ContractEventsParams are the query parameters for ContractEvents.
type ContractEventsParams struct {
	Type       string
	Topic      string
	Topic0     string
	Topic1     string
	Topic2     string
	Topic3     string
	FromLedger int64
	ToLedger   int64
	FromTime   string
	ToTime     string
	Limit      int64
	Cursor     string
	Order      string
	OrderBy    string
	Decoded    string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p ContractEventsParams) values() url.Values {
	v := url.Values{}
	if p.Type != "" {
		v.Set("type", p.Type)
	}
	if p.Topic != "" {
		v.Set("topic", p.Topic)
	}
	if p.Topic0 != "" {
		v.Set("topic0", p.Topic0)
	}
	if p.Topic1 != "" {
		v.Set("topic1", p.Topic1)
	}
	if p.Topic2 != "" {
		v.Set("topic2", p.Topic2)
	}
	if p.Topic3 != "" {
		v.Set("topic3", p.Topic3)
	}
	if p.FromLedger != 0 {
		v.Set("from_ledger", strconv.FormatInt(p.FromLedger, 10))
	}
	if p.ToLedger != 0 {
		v.Set("to_ledger", strconv.FormatInt(p.ToLedger, 10))
	}
	if p.FromTime != "" {
		v.Set("from_time", p.FromTime)
	}
	if p.ToTime != "" {
		v.Set("to_time", p.ToTime)
	}
	if p.Limit != 0 {
		v.Set("limit", strconv.FormatInt(p.Limit, 10))
	}
	if p.Cursor != "" {
		v.Set("cursor", p.Cursor)
	}
	if p.Order != "" {
		v.Set("order", p.Order)
	}
	if p.OrderBy != "" {
		v.Set("order_by", p.OrderBy)
	}
	if p.Decoded != "" {
		v.Set("decoded", p.Decoded)
	}
	return v
}

// ContractExport Export a contract's events.
//
// GET /contracts/{id}/export
func (c *Client) ContractExport(ctx context.Context, id string, params ContractExportParams) ([]byte, error) {
	path := urlEscapePath("/contracts/{id}/export", id)
	query := params.values()
	return doRaw(c, ctx, "GET", path, query, nil)
}

// ContractExportParams are the query parameters for ContractExport.
type ContractExportParams struct {
	FromLedger int64
	ToLedger   int64
	Format     string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p ContractExportParams) values() url.Values {
	v := url.Values{}
	if p.FromLedger != 0 {
		v.Set("from_ledger", strconv.FormatInt(p.FromLedger, 10))
	}
	if p.ToLedger != 0 {
		v.Set("to_ledger", strconv.FormatInt(p.ToLedger, 10))
	}
	if p.Format != "" {
		v.Set("format", p.Format)
	}
	return v
}

// ContractStats Get per-contract statistics.
//
// GET /contracts/{id}/stats
func (c *Client) ContractStats(ctx context.Context, id string) (*ContractStatsResponse, error) {
	path := urlEscapePath("/contracts/{id}/stats", id)
	return do[ContractStatsResponse](c, ctx, "GET", path, nil, nil)
}

// ListDeadLetters List dead-lettered events.
//
// GET /dead-letters
func (c *Client) ListDeadLetters(ctx context.Context, params ListDeadLettersParams) (*ListDeadLettersResponse, error) {
	path := "/dead-letters"
	query := params.values()
	return do[ListDeadLettersResponse](c, ctx, "GET", path, query, nil)
}

// ListDeadLettersParams are the query parameters for ListDeadLetters.
type ListDeadLettersParams struct {
	ContractID string
	Limit      int64
	Cursor     string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p ListDeadLettersParams) values() url.Values {
	v := url.Values{}
	if p.ContractID != "" {
		v.Set("contract_id", p.ContractID)
	}
	if p.Limit != 0 {
		v.Set("limit", strconv.FormatInt(p.Limit, 10))
	}
	if p.Cursor != "" {
		v.Set("cursor", p.Cursor)
	}
	return v
}

// DeleteDeadLetter Discard a dead-lettered event.
//
// DELETE /dead-letters/{id}
func (c *Client) DeleteDeadLetter(ctx context.Context, id int64) error {
	path := urlEscapePath("/dead-letters/{id}", strconv.FormatInt(id, 10))
	return doNoContent(c, ctx, "DELETE", path, nil, nil)
}

// DeleteEvents Prune stored events.
//
// DELETE /events
func (c *Client) DeleteEvents(ctx context.Context, params DeleteEventsParams) (*DeleteEventsResponse, error) {
	path := "/events"
	query := params.values()
	return do[DeleteEventsResponse](c, ctx, "DELETE", path, query, nil)
}

// DeleteEventsParams are the query parameters for DeleteEvents.
type DeleteEventsParams struct {
	BeforeLedger int64
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p DeleteEventsParams) values() url.Values {
	v := url.Values{}
	if p.BeforeLedger != 0 {
		v.Set("before_ledger", strconv.FormatInt(p.BeforeLedger, 10))
	}
	return v
}

// ListEvents List stored events.
//
// GET /events
func (c *Client) ListEvents(ctx context.Context, params ListEventsParams) (*EventsResponse, error) {
	path := "/events"
	query := params.values()
	return do[EventsResponse](c, ctx, "GET", path, query, nil)
}

// ListEventsParams are the query parameters for ListEvents.
type ListEventsParams struct {
	ContractID string
	Type       string
	Topic      string
	Topic0     string
	Topic1     string
	Topic2     string
	Topic3     string
	FromLedger int64
	ToLedger   int64
	FromTime   string
	ToTime     string
	Limit      int64
	Cursor     string
	Order      string
	OrderBy    string
	Decoded    string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p ListEventsParams) values() url.Values {
	v := url.Values{}
	if p.ContractID != "" {
		v.Set("contract_id", p.ContractID)
	}
	if p.Type != "" {
		v.Set("type", p.Type)
	}
	if p.Topic != "" {
		v.Set("topic", p.Topic)
	}
	if p.Topic0 != "" {
		v.Set("topic0", p.Topic0)
	}
	if p.Topic1 != "" {
		v.Set("topic1", p.Topic1)
	}
	if p.Topic2 != "" {
		v.Set("topic2", p.Topic2)
	}
	if p.Topic3 != "" {
		v.Set("topic3", p.Topic3)
	}
	if p.FromLedger != 0 {
		v.Set("from_ledger", strconv.FormatInt(p.FromLedger, 10))
	}
	if p.ToLedger != 0 {
		v.Set("to_ledger", strconv.FormatInt(p.ToLedger, 10))
	}
	if p.FromTime != "" {
		v.Set("from_time", p.FromTime)
	}
	if p.ToTime != "" {
		v.Set("to_time", p.ToTime)
	}
	if p.Limit != 0 {
		v.Set("limit", strconv.FormatInt(p.Limit, 10))
	}
	if p.Cursor != "" {
		v.Set("cursor", p.Cursor)
	}
	if p.Order != "" {
		v.Set("order", p.Order)
	}
	if p.OrderBy != "" {
		v.Set("order_by", p.OrderBy)
	}
	if p.Decoded != "" {
		v.Set("decoded", p.Decoded)
	}
	return v
}

// EventsCSV Export events as CSV.
//
// GET /events.csv
func (c *Client) EventsCSV(ctx context.Context, params EventsCSVParams) ([]byte, error) {
	path := "/events.csv"
	query := params.values()
	return doRaw(c, ctx, "GET", path, query, nil)
}

// EventsCSVParams are the query parameters for EventsCSV.
type EventsCSVParams struct {
	ContractID string
	Type       string
	Topic      string
	Topic0     string
	Topic1     string
	Topic2     string
	Topic3     string
	FromLedger int64
	ToLedger   int64
	FromTime   string
	ToTime     string
	Order      string
	OrderBy    string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p EventsCSVParams) values() url.Values {
	v := url.Values{}
	if p.ContractID != "" {
		v.Set("contract_id", p.ContractID)
	}
	if p.Type != "" {
		v.Set("type", p.Type)
	}
	if p.Topic != "" {
		v.Set("topic", p.Topic)
	}
	if p.Topic0 != "" {
		v.Set("topic0", p.Topic0)
	}
	if p.Topic1 != "" {
		v.Set("topic1", p.Topic1)
	}
	if p.Topic2 != "" {
		v.Set("topic2", p.Topic2)
	}
	if p.Topic3 != "" {
		v.Set("topic3", p.Topic3)
	}
	if p.FromLedger != 0 {
		v.Set("from_ledger", strconv.FormatInt(p.FromLedger, 10))
	}
	if p.ToLedger != 0 {
		v.Set("to_ledger", strconv.FormatInt(p.ToLedger, 10))
	}
	if p.FromTime != "" {
		v.Set("from_time", p.FromTime)
	}
	if p.ToTime != "" {
		v.Set("to_time", p.ToTime)
	}
	if p.Order != "" {
		v.Set("order", p.Order)
	}
	if p.OrderBy != "" {
		v.Set("order_by", p.OrderBy)
	}
	return v
}

// AggregateEvents Aggregate event counts.
//
// GET /events/aggregate
func (c *Client) AggregateEvents(ctx context.Context, params AggregateEventsParams) (*AggregateEventsResponse, error) {
	path := "/events/aggregate"
	query := params.values()
	return do[AggregateEventsResponse](c, ctx, "GET", path, query, nil)
}

// AggregateEventsParams are the query parameters for AggregateEvents.
type AggregateEventsParams struct {
	ContractID string
	Type       string
	Topic      string
	Topic0     string
	Topic1     string
	Topic2     string
	Topic3     string
	FromLedger int64
	ToLedger   int64
	FromTime   string
	ToTime     string
	Bucket     string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p AggregateEventsParams) values() url.Values {
	v := url.Values{}
	if p.ContractID != "" {
		v.Set("contract_id", p.ContractID)
	}
	if p.Type != "" {
		v.Set("type", p.Type)
	}
	if p.Topic != "" {
		v.Set("topic", p.Topic)
	}
	if p.Topic0 != "" {
		v.Set("topic0", p.Topic0)
	}
	if p.Topic1 != "" {
		v.Set("topic1", p.Topic1)
	}
	if p.Topic2 != "" {
		v.Set("topic2", p.Topic2)
	}
	if p.Topic3 != "" {
		v.Set("topic3", p.Topic3)
	}
	if p.FromLedger != 0 {
		v.Set("from_ledger", strconv.FormatInt(p.FromLedger, 10))
	}
	if p.ToLedger != 0 {
		v.Set("to_ledger", strconv.FormatInt(p.ToLedger, 10))
	}
	if p.FromTime != "" {
		v.Set("from_time", p.FromTime)
	}
	if p.ToTime != "" {
		v.Set("to_time", p.ToTime)
	}
	if p.Bucket != "" {
		v.Set("bucket", p.Bucket)
	}
	return v
}

// CountEvents Count matching events.
//
// GET /events/count
func (c *Client) CountEvents(ctx context.Context, params CountEventsParams) (*CountEventsResponse, error) {
	path := "/events/count"
	query := params.values()
	return do[CountEventsResponse](c, ctx, "GET", path, query, nil)
}

// CountEventsParams are the query parameters for CountEvents.
type CountEventsParams struct {
	ContractID string
	Type       string
	Topic      string
	Topic0     string
	Topic1     string
	Topic2     string
	Topic3     string
	FromLedger int64
	ToLedger   int64
	FromTime   string
	ToTime     string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p CountEventsParams) values() url.Values {
	v := url.Values{}
	if p.ContractID != "" {
		v.Set("contract_id", p.ContractID)
	}
	if p.Type != "" {
		v.Set("type", p.Type)
	}
	if p.Topic != "" {
		v.Set("topic", p.Topic)
	}
	if p.Topic0 != "" {
		v.Set("topic0", p.Topic0)
	}
	if p.Topic1 != "" {
		v.Set("topic1", p.Topic1)
	}
	if p.Topic2 != "" {
		v.Set("topic2", p.Topic2)
	}
	if p.Topic3 != "" {
		v.Set("topic3", p.Topic3)
	}
	if p.FromLedger != 0 {
		v.Set("from_ledger", strconv.FormatInt(p.FromLedger, 10))
	}
	if p.ToLedger != 0 {
		v.Set("to_ledger", strconv.FormatInt(p.ToLedger, 10))
	}
	if p.FromTime != "" {
		v.Set("from_time", p.FromTime)
	}
	if p.ToTime != "" {
		v.Set("to_time", p.ToTime)
	}
	return v
}

// EventStreamWS WebSocket live event stream.
//
// GET /events/ws
func (c *Client) EventStreamWS(ctx context.Context, params EventStreamWSParams) error {
	path := "/events/ws"
	query := params.values()
	return doNoContent(c, ctx, "GET", path, query, nil)
}

// EventStreamWSParams are the query parameters for EventStreamWS.
type EventStreamWSParams struct {
	ContractID string
	Type       string
	Topic      string
	Topic0     string
	Topic1     string
	Topic2     string
	Topic3     string
	FromLedger int64
	ToLedger   int64
	FromTime   string
	ToTime     string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p EventStreamWSParams) values() url.Values {
	v := url.Values{}
	if p.ContractID != "" {
		v.Set("contract_id", p.ContractID)
	}
	if p.Type != "" {
		v.Set("type", p.Type)
	}
	if p.Topic != "" {
		v.Set("topic", p.Topic)
	}
	if p.Topic0 != "" {
		v.Set("topic0", p.Topic0)
	}
	if p.Topic1 != "" {
		v.Set("topic1", p.Topic1)
	}
	if p.Topic2 != "" {
		v.Set("topic2", p.Topic2)
	}
	if p.Topic3 != "" {
		v.Set("topic3", p.Topic3)
	}
	if p.FromLedger != 0 {
		v.Set("from_ledger", strconv.FormatInt(p.FromLedger, 10))
	}
	if p.ToLedger != 0 {
		v.Set("to_ledger", strconv.FormatInt(p.ToLedger, 10))
	}
	if p.FromTime != "" {
		v.Set("from_time", p.FromTime)
	}
	if p.ToTime != "" {
		v.Set("to_time", p.ToTime)
	}
	return v
}

// GetEvent Get a single event by ID.
//
// GET /events/{id}
func (c *Client) GetEvent(ctx context.Context, id string, params GetEventParams) (*GetEventResponse, error) {
	path := urlEscapePath("/events/{id}", id)
	query := params.values()
	return do[GetEventResponse](c, ctx, "GET", path, query, nil)
}

// GetEventParams are the query parameters for GetEvent.
type GetEventParams struct {
	Decoded string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p GetEventParams) values() url.Values {
	v := url.Values{}
	if p.Decoded != "" {
		v.Set("decoded", p.Decoded)
	}
	return v
}

// RawEvent Get an event's raw XDR.
//
// GET /events/{id}/raw
func (c *Client) RawEvent(ctx context.Context, id string) (*RawEventResponse, error) {
	path := urlEscapePath("/events/{id}/raw", id)
	return do[RawEventResponse](c, ctx, "GET", path, nil, nil)
}

// EventTransaction Get an event's sibling events.
//
// GET /events/{id}/transaction
func (c *Client) EventTransaction(ctx context.Context, id string, params EventTransactionParams) ([]Event, error) {
	path := urlEscapePath("/events/{id}/transaction", id)
	query := params.values()
	return doSlice[Event](c, ctx, "GET", path, query, nil)
}

// EventTransactionParams are the query parameters for EventTransaction.
type EventTransactionParams struct {
	Decoded string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p EventTransactionParams) values() url.Values {
	v := url.Values{}
	if p.Decoded != "" {
		v.Set("decoded", p.Decoded)
	}
	return v
}

// Health Dependency health check.
//
// GET /health
func (c *Client) Health(ctx context.Context) (*HealthResponse, error) {
	path := "/health"
	return do[HealthResponse](c, ctx, "GET", path, nil, nil)
}

// Livez Liveness probe.
//
// GET /livez
func (c *Client) Livez(ctx context.Context) (*HealthResponse, error) {
	path := "/livez"
	return do[HealthResponse](c, ctx, "GET", path, nil, nil)
}

// Metrics Prometheus metrics.
//
// GET /metrics
func (c *Client) Metrics(ctx context.Context) ([]byte, error) {
	path := "/metrics"
	return doRaw(c, ctx, "GET", path, nil, nil)
}

// Readyz Readiness probe.
//
// GET /readyz
func (c *Client) Readyz(ctx context.Context) (*HealthResponse, error) {
	path := "/readyz"
	return do[HealthResponse](c, ctx, "GET", path, nil, nil)
}

// Stats Indexer statistics.
//
// GET /stats
func (c *Client) Stats(ctx context.Context) (*Stats, error) {
	path := "/stats"
	return do[Stats](c, ctx, "GET", path, nil, nil)
}

// ListSubscriptions List all webhook subscriptions.
//
// GET /subscriptions
func (c *Client) ListSubscriptions(ctx context.Context) ([]Subscription, error) {
	path := "/subscriptions"
	return doSlice[Subscription](c, ctx, "GET", path, nil, nil)
}

// CreateSubscription Register a new webhook subscription.
//
// POST /subscriptions
func (c *Client) CreateSubscription(ctx context.Context, body CreateSubscriptionRequest) (*Subscription, error) {
	path := "/subscriptions"
	return do[Subscription](c, ctx, "POST", path, nil, body)
}

// DeleteSubscription Delete a subscription and its delivery history.
//
// DELETE /subscriptions/{id}
func (c *Client) DeleteSubscription(ctx context.Context, id int64) error {
	path := urlEscapePath("/subscriptions/{id}", strconv.FormatInt(id, 10))
	return doNoContent(c, ctx, "DELETE", path, nil, nil)
}

// GetSubscription Get a single subscription by ID.
//
// GET /subscriptions/{id}
func (c *Client) GetSubscription(ctx context.Context, id int64) (*Subscription, error) {
	path := urlEscapePath("/subscriptions/{id}", strconv.FormatInt(id, 10))
	return do[Subscription](c, ctx, "GET", path, nil, nil)
}

// UpdateSubscription Update a subscription.
//
// PUT /subscriptions/{id}
func (c *Client) UpdateSubscription(ctx context.Context, id int64, body UpdateSubscriptionRequest) (*Subscription, error) {
	path := urlEscapePath("/subscriptions/{id}", strconv.FormatInt(id, 10))
	return do[Subscription](c, ctx, "PUT", path, nil, body)
}

// ListDeliveries List delivery attempts for a subscription.
//
// GET /subscriptions/{id}/deliveries
func (c *Client) ListDeliveries(ctx context.Context, id int64, params ListDeliveriesParams) ([]DeliveryAttempt, error) {
	path := urlEscapePath("/subscriptions/{id}/deliveries", strconv.FormatInt(id, 10))
	query := params.values()
	return doSlice[DeliveryAttempt](c, ctx, "GET", path, query, nil)
}

// ListDeliveriesParams are the query parameters for ListDeliveries.
type ListDeliveriesParams struct {
	Limit int64
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p ListDeliveriesParams) values() url.Values {
	v := url.Values{}
	if p.Limit != 0 {
		v.Set("limit", strconv.FormatInt(p.Limit, 10))
	}
	return v
}

// CurrentTenant Describe the calling tenant.
//
// GET /tenant
func (c *Client) CurrentTenant(ctx context.Context) (*CurrentTenantResponse, error) {
	path := "/tenant"
	return do[CurrentTenantResponse](c, ctx, "GET", path, nil, nil)
}

// CurrentTenantUsage Usage for the calling tenant.
//
// GET /tenant/usage
func (c *Client) CurrentTenantUsage(ctx context.Context, params CurrentTenantUsageParams) (*CurrentTenantUsageResponse, error) {
	path := "/tenant/usage"
	query := params.values()
	return do[CurrentTenantUsageResponse](c, ctx, "GET", path, query, nil)
}

// CurrentTenantUsageParams are the query parameters for CurrentTenantUsage.
type CurrentTenantUsageParams struct {
	Days int64
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p CurrentTenantUsageParams) values() url.Values {
	v := url.Values{}
	if p.Days != 0 {
		v.Set("days", strconv.FormatInt(p.Days, 10))
	}
	return v
}

// TenantWatchList List the tenant's watched contracts.
//
// GET /tenant/watch
func (c *Client) TenantWatchList(ctx context.Context) (*TenantWatchListResponse, error) {
	path := "/tenant/watch"
	return do[TenantWatchListResponse](c, ctx, "GET", path, nil, nil)
}

// AddTenantWatch Add a contract to the tenant's watch list.
//
// POST /tenant/watch
func (c *Client) AddTenantWatch(ctx context.Context) (*AddTenantWatchResponse, error) {
	path := "/tenant/watch"
	return do[AddTenantWatchResponse](c, ctx, "POST", path, nil, nil)
}

// RemoveTenantWatch Remove a contract from the tenant's watch list.
//
// DELETE /tenant/watch/{contract_id}
func (c *Client) RemoveTenantWatch(ctx context.Context, contractID string) (*RemoveTenantWatchResponse, error) {
	path := urlEscapePath("/tenant/watch/{contract_id}", contractID)
	return do[RemoveTenantWatchResponse](c, ctx, "DELETE", path, nil, nil)
}

// Version Build version information.
//
// GET /version
func (c *Client) Version(ctx context.Context) (*VersionResponse, error) {
	path := "/version"
	return do[VersionResponse](c, ctx, "GET", path, nil, nil)
}

// ListWatchedContracts List watched contracts.
//
// GET /watched-contracts
func (c *Client) ListWatchedContracts(ctx context.Context) (*ListWatchedContractsResponse, error) {
	path := "/watched-contracts"
	return do[ListWatchedContractsResponse](c, ctx, "GET", path, nil, nil)
}

// AddWatchedContract Add a watched contract.
//
// POST /watched-contracts
func (c *Client) AddWatchedContract(ctx context.Context) (*AddWatchedContractResponse, error) {
	path := "/watched-contracts"
	return do[AddWatchedContractResponse](c, ctx, "POST", path, nil, nil)
}

// RemoveWatchedContract Stop watching a contract.
//
// DELETE /watched-contracts/{id}
func (c *Client) RemoveWatchedContract(ctx context.Context, id string, params RemoveWatchedContractParams) (*RemoveWatchedContractResponse, error) {
	path := urlEscapePath("/watched-contracts/{id}", id)
	query := params.values()
	return do[RemoveWatchedContractResponse](c, ctx, "DELETE", path, query, nil)
}

// RemoveWatchedContractParams are the query parameters for RemoveWatchedContract.
type RemoveWatchedContractParams struct {
	Confirm string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p RemoveWatchedContractParams) values() url.Values {
	v := url.Values{}
	if p.Confirm != "" {
		v.Set("confirm", p.Confirm)
	}
	return v
}
