// Code generated by cmd/clientgen from api/openapi.yaml; DO NOT EDIT.
//
// The generated surface (types, per-operation methods, SpecRoutes and
// SpecVersion) is verified against api/openapi.yaml by
// pkg/client/drift_test.go. Regenerate with `make client` after
// changing the spec.
package client

import (
	"context"
	"encoding/json"
	"net/url"
	"strconv"
)

// SpecVersion is the api/openapi.yaml info.version this client was
// generated from. A client built against a different spec version may
// not be wire-compatible with a running server.
const SpecVersion = "0.1.0"

// SpecRoute is one (method, path) pair documented in the spec.
type SpecRoute struct {
	Method string
	Path   string
}

// SpecRoutes lists every (method, path) pair in api/openapi.yaml at
// generation time. pkg/client/drift_test.go compares it against the live
// spec so the client can never silently drift from the documented API.
var SpecRoutes = []SpecRoute{
	{Method: "GET", Path: "/addresses/{address}/events"},
	{Method: "GET", Path: "/addresses/{address}/summary"},
	{Method: "DELETE", Path: "/admin/keys/{key_id}"},
	{Method: "GET", Path: "/admin/tenants"},
	{Method: "POST", Path: "/admin/tenants"},
	{Method: "DELETE", Path: "/admin/tenants/{id}"},
	{Method: "GET", Path: "/admin/tenants/{id}"},
	{Method: "PATCH", Path: "/admin/tenants/{id}"},
	{Method: "GET", Path: "/admin/tenants/{id}/grants"},
	{Method: "POST", Path: "/admin/tenants/{id}/grants"},
	{Method: "DELETE", Path: "/admin/tenants/{id}/grants/{contract_id}"},
	{Method: "GET", Path: "/admin/tenants/{id}/keys"},
	{Method: "POST", Path: "/admin/tenants/{id}/keys"},
	{Method: "GET", Path: "/admin/tenants/{id}/usage"},
	{Method: "GET", Path: "/apikeys"},
	{Method: "POST", Path: "/apikeys"},
	{Method: "DELETE", Path: "/apikeys/{id}"},
	{Method: "GET", Path: "/contracts"},
	{Method: "GET", Path: "/contracts/{id}"},
	{Method: "GET", Path: "/contracts/{id}/events"},
	{Method: "GET", Path: "/contracts/{id}/export"},
	{Method: "DELETE", Path: "/contracts/{id}/spec"},
	{Method: "GET", Path: "/contracts/{id}/spec"},
	{Method: "PUT", Path: "/contracts/{id}/spec"},
	{Method: "GET", Path: "/contracts/{id}/stats"},
	{Method: "GET", Path: "/dead-letters"},
	{Method: "DELETE", Path: "/dead-letters/{id}"},
	{Method: "DELETE", Path: "/events"},
	{Method: "GET", Path: "/events"},
	{Method: "GET", Path: "/events.csv"},
	{Method: "GET", Path: "/events/aggregate"},
	{Method: "GET", Path: "/events/count"},
	{Method: "GET", Path: "/events/ws"},
	{Method: "GET", Path: "/events/{id}"},
	{Method: "GET", Path: "/events/{id}/raw"},
	{Method: "GET", Path: "/events/{id}/transaction"},
	{Method: "GET", Path: "/health"},
	{Method: "GET", Path: "/livez"},
	{Method: "GET", Path: "/metrics"},
	{Method: "GET", Path: "/readyz"},
	{Method: "GET", Path: "/stats"},
	{Method: "GET", Path: "/subscriptions"},
	{Method: "POST", Path: "/subscriptions"},
	{Method: "DELETE", Path: "/subscriptions/{id}"},
	{Method: "GET", Path: "/subscriptions/{id}"},
	{Method: "PUT", Path: "/subscriptions/{id}"},
	{Method: "GET", Path: "/subscriptions/{id}/deliveries"},
	{Method: "GET", Path: "/tenant"},
	{Method: "GET", Path: "/tenant/usage"},
	{Method: "GET", Path: "/tenant/watch"},
	{Method: "POST", Path: "/tenant/watch"},
	{Method: "DELETE", Path: "/tenant/watch/{contract_id}"},
	{Method: "GET", Path: "/version"},
	{Method: "GET", Path: "/watched-contracts"},
	{Method: "POST", Path: "/watched-contracts"},
	{Method: "DELETE", Path: "/watched-contracts/{id}"},
}

type APIKey struct {
	CreatedAt string `json:"created_at"`
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Prefix    string `json:"prefix"`
	RevokedAt string `json:"revoked_at,omitempty"`
}

type APIKeyRequest struct {
	Name string `json:"name,omitempty"`
}

type AddressSummary struct {
	Address           string   `json:"address"`
	DistinctContracts []string `json:"distinct_contracts"`
	EventCount        int64    `json:"event_count"`
	FirstSeenLedger   int64    `json:"first_seen_ledger"`
	LastSeenLedger    int64    `json:"last_seen_ledger"`
}

type AggregateBucket struct {
	Bucket string `json:"bucket"`
	Count  int64  `json:"count"`
}

type AggregateResponse struct {
	Buckets []AggregateBucket `json:"buckets"`
}

type ContractListEnvelope struct {
	Data       []ContractSummary `json:"data"`
	NextCursor string            `json:"next_cursor,omitempty"`
}

type ContractListResponse = ContractsPage

type ContractSpecOverrideRequest struct {
	Spec map[string]any `json:"spec"`
}

type ContractSummary struct {
	ContractID  string `json:"contract_id"`
	EventCount  int64  `json:"event_count"`
	FirstLedger int64  `json:"first_ledger"`
	LastLedger  int64  `json:"last_ledger"`
	LastSeen    string `json:"last_seen"`
}

type ContractsPage struct {
	Contracts []ContractSummary `json:"contracts"`
	Count     int64             `json:"count"`
	Cursor    string            `json:"cursor,omitempty"`
}

type CreateSubscriptionRequest struct {
	Enabled bool               `json:"enabled,omitempty"`
	Filters SubscriptionFilter `json:"filters,omitempty"`
	Secret  string             `json:"secret"`
	Url     string             `json:"url"`
}

type CurrentTenant struct {
	GrantedContractIds []string `json:"granted_contract_ids,omitempty"`
	Tenant             Tenant   `json:"tenant"`
	Wildcard           bool     `json:"wildcard"`
}

type DeadLetter struct {
	Attempts    int64    `json:"attempts"`
	ContractID  string   `json:"contract_id"`
	CreatedAt   string   `json:"created_at"`
	Error       string   `json:"error"`
	EventID     string   `json:"event_id"`
	ID          int64    `json:"id"`
	LastAttempt string   `json:"last_attempt"`
	Ledger      int64    `json:"ledger"`
	TopicXdr    []string `json:"topic_xdr,omitempty"`
	TxHash      string   `json:"tx_hash"`
	Type        string   `json:"type"`
	ValueXdr    string   `json:"value_xdr,omitempty"`
}

type DeadLettersEnvelope struct {
	Data       []DeadLetter `json:"data"`
	NextCursor string       `json:"next_cursor,omitempty"`
}

type DeadLettersPage struct {
	Count       int64        `json:"count"`
	Cursor      string       `json:"cursor,omitempty"`
	DeadLetters []DeadLetter `json:"dead_letters"`
}

type DeliveryAttempt struct {
	CreatedAt      string `json:"created_at"`
	DurationMs     int64  `json:"duration_ms"`
	Error          string `json:"error,omitempty"`
	EventID        string `json:"event_id"`
	ID             int64  `json:"id"`
	ResponseCode   int64  `json:"response_code"`
	Status         string `json:"status"`
	SubscriptionID int64  `json:"subscription_id"`
}

type DeliveryEnvelopeResponse struct {
	Data       []DeliveryAttempt `json:"data"`
	NextCursor string            `json:"next_cursor,omitempty"`
}

type EnrichedEvent map[string]any

type ErrorResponse struct {
	Error string `json:"error"`
}

type Event struct {
	ContractID       string `json:"contract_id"`
	CreatedAt        string `json:"created_at"`
	ID               string `json:"id"`
	InSuccessfulCall bool   `json:"in_successful_call"`
	Ledger           int64  `json:"ledger"`
	Network          string `json:"network"`
	OpIndex          int64  `json:"op_index"`
	Sep41Event       any    `json:"sep41_event,omitempty"`
	Topics           []any  `json:"topics"`
	TxHash           string `json:"tx_hash"`
	TxIndex          int64  `json:"tx_index"`
	Type             string `json:"type"`
	Value            any    `json:"value"`
}

type EventEnvelopeResponse struct {
	Data       []any  `json:"data"`
	NextCursor string `json:"next_cursor,omitempty"`
}

type EventListResponse = EventsResponse

type EventResponse map[string]any

type EventWithXDR struct {
	TopicsXdr json.RawMessage `json:"topics_xdr"`
	ValueXdr  json.RawMessage `json:"value_xdr,omitempty"`
}

type EventsResponse struct {
	Cursor string `json:"cursor,omitempty"`
	Events []any  `json:"events"`
}

type GrantContractRequest struct {
	ContractID string `json:"contract_id"`
}

type GrantList struct {
	ContractIds []string `json:"contract_ids"`
}

type HealthResponse struct {
	Checks map[string]any `json:"checks"`
	Status string         `json:"status"`
}

type ProjectedEvent map[string]any

type Stats struct {
	Auditor             json.RawMessage `json:"auditor,omitempty"`
	ChainHeadLedger     json.RawMessage `json:"chain_head_ledger,omitempty"`
	ContractCount       int64           `json:"contract_count,omitempty"`
	Decode              json.RawMessage `json:"decode,omitempty"`
	EventsIngestedTotal int64           `json:"events_ingested_total,omitempty"`
	IngestLagLedgers    json.RawMessage `json:"ingest_lag_ledgers,omitempty"`
	Ingester            struct {
		EffectivePollIntervalMs int64 `json:"effective_poll_interval_ms,omitempty"`
	} `json:"ingester,omitempty"`
	LastIngestedLedger int64  `json:"last_ingested_ledger,omitempty"`
	LastSuccessfulPoll string `json:"last_successful_poll,omitempty"`
	OldestStoredLedger int64  `json:"oldest_stored_ledger,omitempty"`
	PanicsRecovered    int64  `json:"panics_recovered,omitempty"`
	Pruner             struct {
		RunsCompleted   int64 `json:"runs_completed,omitempty"`
		TotalRowsPurged int64 `json:"total_rows_purged,omitempty"`
	} `json:"pruner,omitempty"`
	QueryErrors int64 `json:"query_errors,omitempty"`
	RpcErrors   struct {
		GetEvents        int64 `json:"getEvents,omitempty"`
		GetHealth        int64 `json:"getHealth,omitempty"`
		GetLatestLedger  int64 `json:"getLatestLedger,omitempty"`
		GetLedgerEntries int64 `json:"getLedgerEntries,omitempty"`
	} `json:"rpc_errors,omitempty"`
	SpecCache struct {
		CachedSpecs   int64 `json:"cached_specs,omitempty"`
		Expiries      int64 `json:"expiries,omitempty"`
		Fetches       int64 `json:"fetches,omitempty"`
		Hits          int64 `json:"hits,omitempty"`
		Invalidations int64 `json:"invalidations,omitempty"`
		Misses        int64 `json:"misses,omitempty"`
	} `json:"spec_cache,omitempty"`
	TableSizeBytes        int64 `json:"table_size_bytes,omitempty"`
	TotalEvents           int64 `json:"total_events,omitempty"`
	VerifiedThroughLedger int64 `json:"verified_through_ledger,omitempty"`
	WatchedContracts      int64 `json:"watched_contracts,omitempty"`
}

type Subscription struct {
	CreatedAt    string             `json:"created_at"`
	Enabled      bool               `json:"enabled"`
	FailureCount int64              `json:"failure_count"`
	Filters      SubscriptionFilter `json:"filters"`
	ID           int64              `json:"id"`
	Secret       string             `json:"secret"`
	TenantID     int64              `json:"tenant_id,omitempty"`
	Url          string             `json:"url"`
}

type SubscriptionFilter struct {
	ContractID string `json:"contract_id,omitempty"`
	FromLedger int64  `json:"from_ledger,omitempty"`
	Network    string `json:"network,omitempty"`
	ToLedger   int64  `json:"to_ledger,omitempty"`
	Topic      any    `json:"topic,omitempty"`
	Type       string `json:"type,omitempty"`
}

type Tenant struct {
	Admin               bool            `json:"admin"`
	CreatedAt           string          `json:"created_at"`
	Enabled             bool            `json:"enabled"`
	ID                  int64           `json:"id"`
	MaxWatchedContracts json.RawMessage `json:"max_watched_contracts,omitempty"`
	Name                string          `json:"name"`
	RateLimitBurst      json.RawMessage `json:"rate_limit_burst,omitempty"`
	RateLimitRps        json.RawMessage `json:"rate_limit_rps,omitempty"`
	Wildcard            bool            `json:"wildcard"`
}

type TenantAPIKey struct {
	CreatedAt  string `json:"created_at"`
	ID         int64  `json:"id"`
	LastUsedAt string `json:"last_used_at,omitempty"`
	Name       string `json:"name"`
	Prefix     string `json:"prefix"`
	RevokedAt  string `json:"revoked_at,omitempty"`
	Secret     string `json:"secret,omitempty"`
	TenantID   int64  `json:"tenant_id"`
}

type TenantAPIKeyRequest struct {
	Name string `json:"name,omitempty"`
}

type TenantAPIKeysPage struct {
	Keys []TenantAPIKey `json:"keys"`
}

type TenantCreateRequest struct {
	Admin               bool    `json:"admin,omitempty"`
	Enabled             bool    `json:"enabled,omitempty"`
	MaxWatchedContracts int64   `json:"max_watched_contracts,omitempty"`
	Name                string  `json:"name"`
	RateLimitBurst      int64   `json:"rate_limit_burst,omitempty"`
	RateLimitRps        float64 `json:"rate_limit_rps,omitempty"`
	Wildcard            bool    `json:"wildcard,omitempty"`
}

type TenantList struct {
	Tenants []Tenant `json:"tenants"`
}

type TenantUpdateRequest struct {
	Admin               bool    `json:"admin,omitempty"`
	Enabled             bool    `json:"enabled,omitempty"`
	MaxWatchedContracts int64   `json:"max_watched_contracts,omitempty"`
	Name                string  `json:"name,omitempty"`
	RateLimitBurst      int64   `json:"rate_limit_burst,omitempty"`
	RateLimitRps        float64 `json:"rate_limit_rps,omitempty"`
	Wildcard            bool    `json:"wildcard,omitempty"`
}

type TenantUsage struct {
	Day           string `json:"day"`
	EventsServed  int64  `json:"events_served"`
	Requests      int64  `json:"requests"`
	StreamSeconds int64  `json:"stream_seconds"`
	TenantID      int64  `json:"tenant_id"`
}

type TenantWatchList struct {
	ContractIds []string `json:"contract_ids"`
}

type UpdateSubscriptionRequest struct {
	Enabled bool               `json:"enabled,omitempty"`
	Filters SubscriptionFilter `json:"filters,omitempty"`
	Secret  string             `json:"secret,omitempty"`
	Url     string             `json:"url,omitempty"`
}

type UsagePage struct {
	Usage []TenantUsage `json:"usage"`
}

type WatchedContract struct {
	AddedAt    string `json:"added_at"`
	ContractID string `json:"contract_id"`
}

type WatchedContractAdded struct {
	AddedAt           string `json:"added_at"`
	ContractID        string `json:"contract_id"`
	HistoryFromLedger int64  `json:"history_from_ledger"`
	ModeTransition    string `json:"mode_transition,omitempty"`
}

type WatchedContractRemoved struct {
	ContractID       string `json:"contract_id"`
	HistoryPreserved bool   `json:"history_preserved"`
	ModeTransition   string `json:"mode_transition,omitempty"`
	RemovedAt        string `json:"removed_at"`
}

type WatchedContractRequest struct {
	ContractID string `json:"contract_id"`
}

type WatchedContractsPage struct {
	Contracts []WatchedContract `json:"contracts"`
	Count     int64             `json:"count"`
}

type ContractStatsResponse struct {
	ContractID    string `json:"contract_id"`
	Decimals      int64  `json:"decimals,omitempty"`
	EventCount    int64  `json:"event_count"`
	Name          string `json:"name,omitempty"`
	Symbol        string `json:"symbol,omitempty"`
	TypeBreakdown []struct {
		Count int64  `json:"count"`
		Type  string `json:"type"`
	} `json:"type_breakdown,omitempty"`
}

type CountEventsResponse struct {
	Count int64 `json:"count,omitempty"`
}

type CreateAPIKeyResponse map[string]any

type DeleteContractSpecOverrideResponse struct {
	ContractID string `json:"contract_id"`
	Deleted    bool   `json:"deleted"`
}

type DeleteEventsResponse struct {
	Deleted int64 `json:"deleted,omitempty"`
}

type GetContractResponse struct {
	ContractID  string `json:"contract_id"`
	EventCount  int64  `json:"event_count"`
	FirstLedger int64  `json:"first_ledger"`
	LastLedger  int64  `json:"last_ledger"`
	LastSeen    string `json:"last_seen"`
}

type GetContractSpecOverrideResponse struct {
	ContractID string         `json:"contract_id"`
	Spec       map[string]any `json:"spec"`
}

type ListDeadLettersResponse = DeadLettersPage

type ListDeliveriesResponse = DeliveryEnvelopeResponse

type PutContractSpecOverrideResponse struct {
	ContractID string         `json:"contract_id"`
	Spec       map[string]any `json:"spec"`
}

type RawEventResponse struct {
	TopicsXdr []string `json:"topics_xdr,omitempty"`
	ValueXdr  string   `json:"value_xdr,omitempty"`
}

type VersionResponse struct {
	BuildDate string `json:"build_date,omitempty"`
	Commit    string `json:"commit,omitempty"`
	Version   string `json:"version,omitempty"`
}

// AddressEvents List events involving an address.
//
// GET /addresses/{address}/events
func (c *Client) AddressEvents(ctx context.Context, address string, params AddressEventsParams) (*EventListResponse, error) {
	path := urlEscapePath("/addresses/{address}/events", address)
	query := params.values()
	return do[EventListResponse](c, ctx, "GET", path, query, nil)
}

// AddressEventsParams are the query parameters for AddressEvents.
type AddressEventsParams struct {
	Type       string
	ContractID string
	FromLedger int64
	ToLedger   int64
	Limit      int64
	Cursor     string
	Order      string
	OrderBy    string
	Recent     string
	Envelope   string
	Pretty     string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p AddressEventsParams) values() url.Values {
	v := url.Values{}
	if p.Type != "" {
		v.Set("type", p.Type)
	}
	if p.ContractID != "" {
		v.Set("contract_id", p.ContractID)
	}
	if p.FromLedger != 0 {
		v.Set("from_ledger", strconv.FormatInt(p.FromLedger, 10))
	}
	if p.ToLedger != 0 {
		v.Set("to_ledger", strconv.FormatInt(p.ToLedger, 10))
	}
	if p.Limit != 0 {
		v.Set("limit", strconv.FormatInt(p.Limit, 10))
	}
	if p.Cursor != "" {
		v.Set("cursor", p.Cursor)
	}
	if p.Order != "" {
		v.Set("order", p.Order)
	}
	if p.OrderBy != "" {
		v.Set("order_by", p.OrderBy)
	}
	if p.Recent != "" {
		v.Set("recent", p.Recent)
	}
	if p.Envelope != "" {
		v.Set("envelope", p.Envelope)
	}
	if p.Pretty != "" {
		v.Set("pretty", p.Pretty)
	}
	return v
}

// AddressSummary Summarise an address's event history.
//
// GET /addresses/{address}/summary
func (c *Client) AddressSummary(ctx context.Context, address string) (*AddressSummary, error) {
	path := urlEscapePath("/addresses/{address}/summary", address)
	return do[AddressSummary](c, ctx, "GET", path, nil, nil)
}

// RevokeKey Revoke an API key.
//
// DELETE /admin/keys/{key_id}
func (c *Client) RevokeKey(ctx context.Context, keyID int64) error {
	path := urlEscapePath("/admin/keys/{key_id}", strconv.FormatInt(keyID, 10))
	return doNoContent(c, ctx, "DELETE", path, nil, nil)
}

// ListTenants List tenants.
//
// GET /admin/tenants
func (c *Client) ListTenants(ctx context.Context) (*TenantList, error) {
	path := "/admin/tenants"
	return do[TenantList](c, ctx, "GET", path, nil, nil)
}

// CreateTenant Create a tenant.
//
// POST /admin/tenants
func (c *Client) CreateTenant(ctx context.Context, body TenantCreateRequest) (*Tenant, error) {
	path := "/admin/tenants"
	return do[Tenant](c, ctx, "POST", path, nil, body)
}

// DeleteTenant Delete a tenant.
//
// DELETE /admin/tenants/{id}
func (c *Client) DeleteTenant(ctx context.Context, id int64) error {
	path := urlEscapePath("/admin/tenants/{id}", strconv.FormatInt(id, 10))
	return doNoContent(c, ctx, "DELETE", path, nil, nil)
}

// GetTenant Get a tenant.
//
// GET /admin/tenants/{id}
func (c *Client) GetTenant(ctx context.Context, id int64) (*Tenant, error) {
	path := urlEscapePath("/admin/tenants/{id}", strconv.FormatInt(id, 10))
	return do[Tenant](c, ctx, "GET", path, nil, nil)
}

// UpdateTenant Update a tenant.
//
// PATCH /admin/tenants/{id}
func (c *Client) UpdateTenant(ctx context.Context, id int64, body TenantUpdateRequest) (*Tenant, error) {
	path := urlEscapePath("/admin/tenants/{id}", strconv.FormatInt(id, 10))
	return do[Tenant](c, ctx, "PATCH", path, nil, body)
}

// ListTenantGrants List a tenant's contract grants.
//
// GET /admin/tenants/{id}/grants
func (c *Client) ListTenantGrants(ctx context.Context, id int64) (*GrantList, error) {
	path := urlEscapePath("/admin/tenants/{id}/grants", strconv.FormatInt(id, 10))
	return do[GrantList](c, ctx, "GET", path, nil, nil)
}

// GrantContract Grant a contract to a tenant.
//
// POST /admin/tenants/{id}/grants
func (c *Client) GrantContract(ctx context.Context, id int64, body GrantContractRequest) (*GrantList, error) {
	path := urlEscapePath("/admin/tenants/{id}/grants", strconv.FormatInt(id, 10))
	return do[GrantList](c, ctx, "POST", path, nil, body)
}

// RevokeContract Revoke a contract grant.
//
// DELETE /admin/tenants/{id}/grants/{contract_id}
func (c *Client) RevokeContract(ctx context.Context, id int64, contractID string) (*GrantList, error) {
	path := urlEscapePath("/admin/tenants/{id}/grants/{contract_id}", strconv.FormatInt(id, 10), contractID)
	return do[GrantList](c, ctx, "DELETE", path, nil, nil)
}

// ListTenantKeys List a tenant's API keys.
//
// GET /admin/tenants/{id}/keys
func (c *Client) ListTenantKeys(ctx context.Context, id int64) (*TenantAPIKeysPage, error) {
	path := urlEscapePath("/admin/tenants/{id}/keys", strconv.FormatInt(id, 10))
	return do[TenantAPIKeysPage](c, ctx, "GET", path, nil, nil)
}

// CreateTenantKey Issue an API key for a tenant.
//
// POST /admin/tenants/{id}/keys
func (c *Client) CreateTenantKey(ctx context.Context, id int64, body TenantAPIKeyRequest) (*TenantAPIKey, error) {
	path := urlEscapePath("/admin/tenants/{id}/keys", strconv.FormatInt(id, 10))
	return do[TenantAPIKey](c, ctx, "POST", path, nil, body)
}

// TenantUsage Get a tenant's recorded usage.
//
// GET /admin/tenants/{id}/usage
func (c *Client) TenantUsage(ctx context.Context, id int64, params TenantUsageParams) (*UsagePage, error) {
	path := urlEscapePath("/admin/tenants/{id}/usage", strconv.FormatInt(id, 10))
	query := params.values()
	return do[UsagePage](c, ctx, "GET", path, query, nil)
}

// TenantUsageParams are the query parameters for TenantUsage.
type TenantUsageParams struct {
	Days int64
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p TenantUsageParams) values() url.Values {
	v := url.Values{}
	if p.Days != 0 {
		v.Set("days", strconv.FormatInt(p.Days, 10))
	}
	return v
}

// ListAPIKeys List API keys.
//
// GET /apikeys
func (c *Client) ListAPIKeys(ctx context.Context) ([]APIKey, error) {
	path := "/apikeys"
	return doSlice[APIKey](c, ctx, "GET", path, nil, nil)
}

// CreateAPIKey Create an API key.
//
// POST /apikeys
func (c *Client) CreateAPIKey(ctx context.Context, body APIKeyRequest) (*CreateAPIKeyResponse, error) {
	path := "/apikeys"
	return do[CreateAPIKeyResponse](c, ctx, "POST", path, nil, body)
}

// RevokeAPIKey Revoke an API key.
//
// DELETE /apikeys/{id}
func (c *Client) RevokeAPIKey(ctx context.Context, id int64) error {
	path := urlEscapePath("/apikeys/{id}", strconv.FormatInt(id, 10))
	return doNoContent(c, ctx, "DELETE", path, nil, nil)
}

// ListContracts List indexed contracts.
//
// GET /contracts
func (c *Client) ListContracts(ctx context.Context, params ListContractsParams) (*ContractListResponse, error) {
	path := "/contracts"
	query := params.values()
	return do[ContractListResponse](c, ctx, "GET", path, query, nil)
}

// ListContractsParams are the query parameters for ListContracts.
type ListContractsParams struct {
	Limit      int64
	Cursor     string
	Sort       string
	Order      string
	ContractID string
	Envelope   string
	Pretty     string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p ListContractsParams) values() url.Values {
	v := url.Values{}
	if p.Limit != 0 {
		v.Set("limit", strconv.FormatInt(p.Limit, 10))
	}
	if p.Cursor != "" {
		v.Set("cursor", p.Cursor)
	}
	if p.Sort != "" {
		v.Set("sort", p.Sort)
	}
	if p.Order != "" {
		v.Set("order", p.Order)
	}
	if p.ContractID != "" {
		v.Set("contract_id", p.ContractID)
	}
	if p.Envelope != "" {
		v.Set("envelope", p.Envelope)
	}
	if p.Pretty != "" {
		v.Set("pretty", p.Pretty)
	}
	return v
}

// GetContract Get a single contract's summary.
//
// GET /contracts/{id}
func (c *Client) GetContract(ctx context.Context, id string) (*GetContractResponse, error) {
	path := urlEscapePath("/contracts/{id}", id)
	return do[GetContractResponse](c, ctx, "GET", path, nil, nil)
}

// ContractEvents List events for a contract.
//
// GET /contracts/{id}/events
func (c *Client) ContractEvents(ctx context.Context, id string, params ContractEventsParams) (*EventListResponse, error) {
	path := urlEscapePath("/contracts/{id}/events", id)
	query := params.values()
	return do[EventListResponse](c, ctx, "GET", path, query, nil)
}

// ContractEventsParams are the query parameters for ContractEvents.
type ContractEventsParams struct {
	Type             string
	Topic            string
	Topic0           string
	Topic1           string
	Topic2           string
	Topic3           string
	FromLedger       int64
	ToLedger         int64
	FromTime         string
	ToTime           string
	Limit            int64
	Cursor           string
	Order            string
	OrderBy          string
	Decoded          string
	TopicContains    string
	TxHash           string
	TxIndex          int64
	OpIndex          int64
	InSuccessfulCall string
	HasValue         string
	Recent           string
	Fields           string
	IncludeXdr       string
	Envelope         string
	Pretty           string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p ContractEventsParams) values() url.Values {
	v := url.Values{}
	if p.Type != "" {
		v.Set("type", p.Type)
	}
	if p.Topic != "" {
		v.Set("topic", p.Topic)
	}
	if p.Topic0 != "" {
		v.Set("topic0", p.Topic0)
	}
	if p.Topic1 != "" {
		v.Set("topic1", p.Topic1)
	}
	if p.Topic2 != "" {
		v.Set("topic2", p.Topic2)
	}
	if p.Topic3 != "" {
		v.Set("topic3", p.Topic3)
	}
	if p.FromLedger != 0 {
		v.Set("from_ledger", strconv.FormatInt(p.FromLedger, 10))
	}
	if p.ToLedger != 0 {
		v.Set("to_ledger", strconv.FormatInt(p.ToLedger, 10))
	}
	if p.FromTime != "" {
		v.Set("from_time", p.FromTime)
	}
	if p.ToTime != "" {
		v.Set("to_time", p.ToTime)
	}
	if p.Limit != 0 {
		v.Set("limit", strconv.FormatInt(p.Limit, 10))
	}
	if p.Cursor != "" {
		v.Set("cursor", p.Cursor)
	}
	if p.Order != "" {
		v.Set("order", p.Order)
	}
	if p.OrderBy != "" {
		v.Set("order_by", p.OrderBy)
	}
	if p.Decoded != "" {
		v.Set("decoded", p.Decoded)
	}
	if p.TopicContains != "" {
		v.Set("topic_contains", p.TopicContains)
	}
	if p.TxHash != "" {
		v.Set("tx_hash", p.TxHash)
	}
	if p.TxIndex != 0 {
		v.Set("tx_index", strconv.FormatInt(p.TxIndex, 10))
	}
	if p.OpIndex != 0 {
		v.Set("op_index", strconv.FormatInt(p.OpIndex, 10))
	}
	if p.InSuccessfulCall != "" {
		v.Set("in_successful_call", p.InSuccessfulCall)
	}
	if p.HasValue != "" {
		v.Set("has_value", p.HasValue)
	}
	if p.Recent != "" {
		v.Set("recent", p.Recent)
	}
	if p.Fields != "" {
		v.Set("fields", p.Fields)
	}
	if p.IncludeXdr != "" {
		v.Set("include_xdr", p.IncludeXdr)
	}
	if p.Envelope != "" {
		v.Set("envelope", p.Envelope)
	}
	if p.Pretty != "" {
		v.Set("pretty", p.Pretty)
	}
	return v
}

// ContractExport Export a contract's events.
//
// GET /contracts/{id}/export
func (c *Client) ContractExport(ctx context.Context, id string, params ContractExportParams) ([]byte, error) {
	path := urlEscapePath("/contracts/{id}/export", id)
	query := params.values()
	return doRaw(c, ctx, "GET", path, query, nil)
}

// ContractExportParams are the query parameters for ContractExport.
type ContractExportParams struct {
	FromLedger int64
	ToLedger   int64
	Format     string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p ContractExportParams) values() url.Values {
	v := url.Values{}
	if p.FromLedger != 0 {
		v.Set("from_ledger", strconv.FormatInt(p.FromLedger, 10))
	}
	if p.ToLedger != 0 {
		v.Set("to_ledger", strconv.FormatInt(p.ToLedger, 10))
	}
	if p.Format != "" {
		v.Set("format", p.Format)
	}
	return v
}

// DeleteContractSpecOverride Delete a contract spec override.
//
// DELETE /contracts/{id}/spec
func (c *Client) DeleteContractSpecOverride(ctx context.Context, id string) (*DeleteContractSpecOverrideResponse, error) {
	path := urlEscapePath("/contracts/{id}/spec", id)
	return do[DeleteContractSpecOverrideResponse](c, ctx, "DELETE", path, nil, nil)
}

// GetContractSpecOverride Get a contract spec override.
//
// GET /contracts/{id}/spec
func (c *Client) GetContractSpecOverride(ctx context.Context, id string) (*GetContractSpecOverrideResponse, error) {
	path := urlEscapePath("/contracts/{id}/spec", id)
	return do[GetContractSpecOverrideResponse](c, ctx, "GET", path, nil, nil)
}

// PutContractSpecOverride Upload a contract spec override.
//
// PUT /contracts/{id}/spec
func (c *Client) PutContractSpecOverride(ctx context.Context, id string, body ContractSpecOverrideRequest) (*PutContractSpecOverrideResponse, error) {
	path := urlEscapePath("/contracts/{id}/spec", id)
	return do[PutContractSpecOverrideResponse](c, ctx, "PUT", path, nil, body)
}

// ContractStats Get per-contract statistics.
//
// GET /contracts/{id}/stats
func (c *Client) ContractStats(ctx context.Context, id string) (*ContractStatsResponse, error) {
	path := urlEscapePath("/contracts/{id}/stats", id)
	return do[ContractStatsResponse](c, ctx, "GET", path, nil, nil)
}

// ListDeadLetters List dead-lettered events.
//
// GET /dead-letters
func (c *Client) ListDeadLetters(ctx context.Context, params ListDeadLettersParams) (*ListDeadLettersResponse, error) {
	path := "/dead-letters"
	query := params.values()
	return do[ListDeadLettersResponse](c, ctx, "GET", path, query, nil)
}

// ListDeadLettersParams are the query parameters for ListDeadLetters.
type ListDeadLettersParams struct {
	ContractID string
	Limit      int64
	Cursor     string
	Envelope   string
	Pretty     string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p ListDeadLettersParams) values() url.Values {
	v := url.Values{}
	if p.ContractID != "" {
		v.Set("contract_id", p.ContractID)
	}
	if p.Limit != 0 {
		v.Set("limit", strconv.FormatInt(p.Limit, 10))
	}
	if p.Cursor != "" {
		v.Set("cursor", p.Cursor)
	}
	if p.Envelope != "" {
		v.Set("envelope", p.Envelope)
	}
	if p.Pretty != "" {
		v.Set("pretty", p.Pretty)
	}
	return v
}

// DeleteDeadLetter Discard a dead-lettered event.
//
// DELETE /dead-letters/{id}
func (c *Client) DeleteDeadLetter(ctx context.Context, id int64) error {
	path := urlEscapePath("/dead-letters/{id}", strconv.FormatInt(id, 10))
	return doNoContent(c, ctx, "DELETE", path, nil, nil)
}

// DeleteEvents Prune stored events.
//
// DELETE /events
func (c *Client) DeleteEvents(ctx context.Context, params DeleteEventsParams) (*DeleteEventsResponse, error) {
	path := "/events"
	query := params.values()
	return do[DeleteEventsResponse](c, ctx, "DELETE", path, query, nil)
}

// DeleteEventsParams are the query parameters for DeleteEvents.
type DeleteEventsParams struct {
	BeforeLedger int64
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p DeleteEventsParams) values() url.Values {
	v := url.Values{}
	if p.BeforeLedger != 0 {
		v.Set("before_ledger", strconv.FormatInt(p.BeforeLedger, 10))
	}
	return v
}

// ListEvents List stored events.
//
// GET /events
func (c *Client) ListEvents(ctx context.Context, params ListEventsParams) (*EventListResponse, error) {
	path := "/events"
	query := params.values()
	return do[EventListResponse](c, ctx, "GET", path, query, nil)
}

// ListEventsParams are the query parameters for ListEvents.
type ListEventsParams struct {
	ContractID       string
	Type             string
	Topic            string
	Topic0           string
	Topic1           string
	Topic2           string
	Topic3           string
	FromLedger       int64
	ToLedger         int64
	FromTime         string
	ToTime           string
	Limit            int64
	Cursor           string
	Order            string
	OrderBy          string
	Decoded          string
	ContractIDPrefix string
	TopicContains    string
	TxHash           string
	TxIndex          int64
	OpIndex          int64
	InSuccessfulCall string
	HasValue         string
	Recent           string
	Fields           string
	IncludeXdr       string
	Stream           string
	Envelope         string
	Pretty           string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p ListEventsParams) values() url.Values {
	v := url.Values{}
	if p.ContractID != "" {
		v.Set("contract_id", p.ContractID)
	}
	if p.Type != "" {
		v.Set("type", p.Type)
	}
	if p.Topic != "" {
		v.Set("topic", p.Topic)
	}
	if p.Topic0 != "" {
		v.Set("topic0", p.Topic0)
	}
	if p.Topic1 != "" {
		v.Set("topic1", p.Topic1)
	}
	if p.Topic2 != "" {
		v.Set("topic2", p.Topic2)
	}
	if p.Topic3 != "" {
		v.Set("topic3", p.Topic3)
	}
	if p.FromLedger != 0 {
		v.Set("from_ledger", strconv.FormatInt(p.FromLedger, 10))
	}
	if p.ToLedger != 0 {
		v.Set("to_ledger", strconv.FormatInt(p.ToLedger, 10))
	}
	if p.FromTime != "" {
		v.Set("from_time", p.FromTime)
	}
	if p.ToTime != "" {
		v.Set("to_time", p.ToTime)
	}
	if p.Limit != 0 {
		v.Set("limit", strconv.FormatInt(p.Limit, 10))
	}
	if p.Cursor != "" {
		v.Set("cursor", p.Cursor)
	}
	if p.Order != "" {
		v.Set("order", p.Order)
	}
	if p.OrderBy != "" {
		v.Set("order_by", p.OrderBy)
	}
	if p.Decoded != "" {
		v.Set("decoded", p.Decoded)
	}
	if p.ContractIDPrefix != "" {
		v.Set("contract_id_prefix", p.ContractIDPrefix)
	}
	if p.TopicContains != "" {
		v.Set("topic_contains", p.TopicContains)
	}
	if p.TxHash != "" {
		v.Set("tx_hash", p.TxHash)
	}
	if p.TxIndex != 0 {
		v.Set("tx_index", strconv.FormatInt(p.TxIndex, 10))
	}
	if p.OpIndex != 0 {
		v.Set("op_index", strconv.FormatInt(p.OpIndex, 10))
	}
	if p.InSuccessfulCall != "" {
		v.Set("in_successful_call", p.InSuccessfulCall)
	}
	if p.HasValue != "" {
		v.Set("has_value", p.HasValue)
	}
	if p.Recent != "" {
		v.Set("recent", p.Recent)
	}
	if p.Fields != "" {
		v.Set("fields", p.Fields)
	}
	if p.IncludeXdr != "" {
		v.Set("include_xdr", p.IncludeXdr)
	}
	if p.Stream != "" {
		v.Set("stream", p.Stream)
	}
	if p.Envelope != "" {
		v.Set("envelope", p.Envelope)
	}
	if p.Pretty != "" {
		v.Set("pretty", p.Pretty)
	}
	return v
}

// EventsCSV Export events as CSV.
//
// GET /events.csv
func (c *Client) EventsCSV(ctx context.Context, params EventsCSVParams) ([]byte, error) {
	path := "/events.csv"
	query := params.values()
	return doRaw(c, ctx, "GET", path, query, nil)
}

// EventsCSVParams are the query parameters for EventsCSV.
type EventsCSVParams struct {
	ContractID       string
	Type             string
	Topic            string
	Topic0           string
	Topic1           string
	Topic2           string
	Topic3           string
	FromLedger       int64
	ToLedger         int64
	FromTime         string
	ToTime           string
	ContractIDPrefix string
	TopicContains    string
	TxHash           string
	TxIndex          int64
	OpIndex          int64
	InSuccessfulCall string
	HasValue         string
	Order            string
	OrderBy          string
	Recent           string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p EventsCSVParams) values() url.Values {
	v := url.Values{}
	if p.ContractID != "" {
		v.Set("contract_id", p.ContractID)
	}
	if p.Type != "" {
		v.Set("type", p.Type)
	}
	if p.Topic != "" {
		v.Set("topic", p.Topic)
	}
	if p.Topic0 != "" {
		v.Set("topic0", p.Topic0)
	}
	if p.Topic1 != "" {
		v.Set("topic1", p.Topic1)
	}
	if p.Topic2 != "" {
		v.Set("topic2", p.Topic2)
	}
	if p.Topic3 != "" {
		v.Set("topic3", p.Topic3)
	}
	if p.FromLedger != 0 {
		v.Set("from_ledger", strconv.FormatInt(p.FromLedger, 10))
	}
	if p.ToLedger != 0 {
		v.Set("to_ledger", strconv.FormatInt(p.ToLedger, 10))
	}
	if p.FromTime != "" {
		v.Set("from_time", p.FromTime)
	}
	if p.ToTime != "" {
		v.Set("to_time", p.ToTime)
	}
	if p.ContractIDPrefix != "" {
		v.Set("contract_id_prefix", p.ContractIDPrefix)
	}
	if p.TopicContains != "" {
		v.Set("topic_contains", p.TopicContains)
	}
	if p.TxHash != "" {
		v.Set("tx_hash", p.TxHash)
	}
	if p.TxIndex != 0 {
		v.Set("tx_index", strconv.FormatInt(p.TxIndex, 10))
	}
	if p.OpIndex != 0 {
		v.Set("op_index", strconv.FormatInt(p.OpIndex, 10))
	}
	if p.InSuccessfulCall != "" {
		v.Set("in_successful_call", p.InSuccessfulCall)
	}
	if p.HasValue != "" {
		v.Set("has_value", p.HasValue)
	}
	if p.Order != "" {
		v.Set("order", p.Order)
	}
	if p.OrderBy != "" {
		v.Set("order_by", p.OrderBy)
	}
	if p.Recent != "" {
		v.Set("recent", p.Recent)
	}
	return v
}

// AggregateEvents Aggregate event counts.
//
// GET /events/aggregate
func (c *Client) AggregateEvents(ctx context.Context, params AggregateEventsParams) (*AggregateResponse, error) {
	path := "/events/aggregate"
	query := params.values()
	return do[AggregateResponse](c, ctx, "GET", path, query, nil)
}

// AggregateEventsParams are the query parameters for AggregateEvents.
type AggregateEventsParams struct {
	ContractID       string
	Type             string
	Topic            string
	Topic0           string
	Topic1           string
	Topic2           string
	Topic3           string
	FromLedger       int64
	ToLedger         int64
	FromTime         string
	ToTime           string
	ContractIDPrefix string
	TopicContains    string
	TxHash           string
	TxIndex          int64
	OpIndex          int64
	InSuccessfulCall string
	HasValue         string
	Bucket           string
	Pretty           string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p AggregateEventsParams) values() url.Values {
	v := url.Values{}
	if p.ContractID != "" {
		v.Set("contract_id", p.ContractID)
	}
	if p.Type != "" {
		v.Set("type", p.Type)
	}
	if p.Topic != "" {
		v.Set("topic", p.Topic)
	}
	if p.Topic0 != "" {
		v.Set("topic0", p.Topic0)
	}
	if p.Topic1 != "" {
		v.Set("topic1", p.Topic1)
	}
	if p.Topic2 != "" {
		v.Set("topic2", p.Topic2)
	}
	if p.Topic3 != "" {
		v.Set("topic3", p.Topic3)
	}
	if p.FromLedger != 0 {
		v.Set("from_ledger", strconv.FormatInt(p.FromLedger, 10))
	}
	if p.ToLedger != 0 {
		v.Set("to_ledger", strconv.FormatInt(p.ToLedger, 10))
	}
	if p.FromTime != "" {
		v.Set("from_time", p.FromTime)
	}
	if p.ToTime != "" {
		v.Set("to_time", p.ToTime)
	}
	if p.ContractIDPrefix != "" {
		v.Set("contract_id_prefix", p.ContractIDPrefix)
	}
	if p.TopicContains != "" {
		v.Set("topic_contains", p.TopicContains)
	}
	if p.TxHash != "" {
		v.Set("tx_hash", p.TxHash)
	}
	if p.TxIndex != 0 {
		v.Set("tx_index", strconv.FormatInt(p.TxIndex, 10))
	}
	if p.OpIndex != 0 {
		v.Set("op_index", strconv.FormatInt(p.OpIndex, 10))
	}
	if p.InSuccessfulCall != "" {
		v.Set("in_successful_call", p.InSuccessfulCall)
	}
	if p.HasValue != "" {
		v.Set("has_value", p.HasValue)
	}
	if p.Bucket != "" {
		v.Set("bucket", p.Bucket)
	}
	if p.Pretty != "" {
		v.Set("pretty", p.Pretty)
	}
	return v
}

// CountEvents Count matching events.
//
// GET /events/count
func (c *Client) CountEvents(ctx context.Context, params CountEventsParams) (*CountEventsResponse, error) {
	path := "/events/count"
	query := params.values()
	return do[CountEventsResponse](c, ctx, "GET", path, query, nil)
}

// CountEventsParams are the query parameters for CountEvents.
type CountEventsParams struct {
	ContractID       string
	Type             string
	Topic            string
	Topic0           string
	Topic1           string
	Topic2           string
	Topic3           string
	FromLedger       int64
	ToLedger         int64
	FromTime         string
	ToTime           string
	ContractIDPrefix string
	TopicContains    string
	TxHash           string
	TxIndex          int64
	OpIndex          int64
	InSuccessfulCall string
	HasValue         string
	Pretty           string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p CountEventsParams) values() url.Values {
	v := url.Values{}
	if p.ContractID != "" {
		v.Set("contract_id", p.ContractID)
	}
	if p.Type != "" {
		v.Set("type", p.Type)
	}
	if p.Topic != "" {
		v.Set("topic", p.Topic)
	}
	if p.Topic0 != "" {
		v.Set("topic0", p.Topic0)
	}
	if p.Topic1 != "" {
		v.Set("topic1", p.Topic1)
	}
	if p.Topic2 != "" {
		v.Set("topic2", p.Topic2)
	}
	if p.Topic3 != "" {
		v.Set("topic3", p.Topic3)
	}
	if p.FromLedger != 0 {
		v.Set("from_ledger", strconv.FormatInt(p.FromLedger, 10))
	}
	if p.ToLedger != 0 {
		v.Set("to_ledger", strconv.FormatInt(p.ToLedger, 10))
	}
	if p.FromTime != "" {
		v.Set("from_time", p.FromTime)
	}
	if p.ToTime != "" {
		v.Set("to_time", p.ToTime)
	}
	if p.ContractIDPrefix != "" {
		v.Set("contract_id_prefix", p.ContractIDPrefix)
	}
	if p.TopicContains != "" {
		v.Set("topic_contains", p.TopicContains)
	}
	if p.TxHash != "" {
		v.Set("tx_hash", p.TxHash)
	}
	if p.TxIndex != 0 {
		v.Set("tx_index", strconv.FormatInt(p.TxIndex, 10))
	}
	if p.OpIndex != 0 {
		v.Set("op_index", strconv.FormatInt(p.OpIndex, 10))
	}
	if p.InSuccessfulCall != "" {
		v.Set("in_successful_call", p.InSuccessfulCall)
	}
	if p.HasValue != "" {
		v.Set("has_value", p.HasValue)
	}
	if p.Pretty != "" {
		v.Set("pretty", p.Pretty)
	}
	return v
}

// EventStreamWS WebSocket live event stream.
//
// GET /events/ws
func (c *Client) EventStreamWS(ctx context.Context, params EventStreamWSParams) error {
	path := "/events/ws"
	query := params.values()
	return doNoContent(c, ctx, "GET", path, query, nil)
}

// EventStreamWSParams are the query parameters for EventStreamWS.
type EventStreamWSParams struct {
	ContractID string
	Type       string
	Topic      string
	FromLedger int64
	ToLedger   int64
	FromTime   string
	ToTime     string
	HasValue   string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p EventStreamWSParams) values() url.Values {
	v := url.Values{}
	if p.ContractID != "" {
		v.Set("contract_id", p.ContractID)
	}
	if p.Type != "" {
		v.Set("type", p.Type)
	}
	if p.Topic != "" {
		v.Set("topic", p.Topic)
	}
	if p.FromLedger != 0 {
		v.Set("from_ledger", strconv.FormatInt(p.FromLedger, 10))
	}
	if p.ToLedger != 0 {
		v.Set("to_ledger", strconv.FormatInt(p.ToLedger, 10))
	}
	if p.FromTime != "" {
		v.Set("from_time", p.FromTime)
	}
	if p.ToTime != "" {
		v.Set("to_time", p.ToTime)
	}
	if p.HasValue != "" {
		v.Set("has_value", p.HasValue)
	}
	return v
}

// GetEvent Get a single event by ID.
//
// GET /events/{id}
func (c *Client) GetEvent(ctx context.Context, id string, params GetEventParams) (*EventResponse, error) {
	path := urlEscapePath("/events/{id}", id)
	query := params.values()
	return do[EventResponse](c, ctx, "GET", path, query, nil)
}

// GetEventParams are the query parameters for GetEvent.
type GetEventParams struct {
	Decoded    string
	Fields     string
	IncludeXdr string
	Pretty     string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p GetEventParams) values() url.Values {
	v := url.Values{}
	if p.Decoded != "" {
		v.Set("decoded", p.Decoded)
	}
	if p.Fields != "" {
		v.Set("fields", p.Fields)
	}
	if p.IncludeXdr != "" {
		v.Set("include_xdr", p.IncludeXdr)
	}
	if p.Pretty != "" {
		v.Set("pretty", p.Pretty)
	}
	return v
}

// RawEvent Get an event's raw XDR.
//
// GET /events/{id}/raw
func (c *Client) RawEvent(ctx context.Context, id string) (*RawEventResponse, error) {
	path := urlEscapePath("/events/{id}/raw", id)
	return do[RawEventResponse](c, ctx, "GET", path, nil, nil)
}

// EventTransaction Get an event's sibling events.
//
// GET /events/{id}/transaction
func (c *Client) EventTransaction(ctx context.Context, id string, params EventTransactionParams) (*EventsResponse, error) {
	path := urlEscapePath("/events/{id}/transaction", id)
	query := params.values()
	return do[EventsResponse](c, ctx, "GET", path, query, nil)
}

// EventTransactionParams are the query parameters for EventTransaction.
type EventTransactionParams struct {
	Decoded    string
	Fields     string
	IncludeXdr string
	Pretty     string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p EventTransactionParams) values() url.Values {
	v := url.Values{}
	if p.Decoded != "" {
		v.Set("decoded", p.Decoded)
	}
	if p.Fields != "" {
		v.Set("fields", p.Fields)
	}
	if p.IncludeXdr != "" {
		v.Set("include_xdr", p.IncludeXdr)
	}
	if p.Pretty != "" {
		v.Set("pretty", p.Pretty)
	}
	return v
}

// Health Dependency health check.
//
// GET /health
func (c *Client) Health(ctx context.Context) (*HealthResponse, error) {
	path := "/health"
	return do[HealthResponse](c, ctx, "GET", path, nil, nil)
}

// Livez Liveness probe.
//
// GET /livez
func (c *Client) Livez(ctx context.Context) (*HealthResponse, error) {
	path := "/livez"
	return do[HealthResponse](c, ctx, "GET", path, nil, nil)
}

// Metrics Prometheus metrics.
//
// GET /metrics
func (c *Client) Metrics(ctx context.Context) ([]byte, error) {
	path := "/metrics"
	return doRaw(c, ctx, "GET", path, nil, nil)
}

// Readyz Readiness probe.
//
// GET /readyz
func (c *Client) Readyz(ctx context.Context) (*HealthResponse, error) {
	path := "/readyz"
	return do[HealthResponse](c, ctx, "GET", path, nil, nil)
}

// Stats Indexer statistics.
//
// GET /stats
func (c *Client) Stats(ctx context.Context) (*Stats, error) {
	path := "/stats"
	return do[Stats](c, ctx, "GET", path, nil, nil)
}

// ListSubscriptions List all webhook subscriptions.
//
// GET /subscriptions
func (c *Client) ListSubscriptions(ctx context.Context) ([]Subscription, error) {
	path := "/subscriptions"
	return doSlice[Subscription](c, ctx, "GET", path, nil, nil)
}

// CreateSubscription Register a new webhook subscription.
//
// POST /subscriptions
func (c *Client) CreateSubscription(ctx context.Context, body CreateSubscriptionRequest) (*Subscription, error) {
	path := "/subscriptions"
	return do[Subscription](c, ctx, "POST", path, nil, body)
}

// DeleteSubscription Delete a subscription and its delivery history.
//
// DELETE /subscriptions/{id}
func (c *Client) DeleteSubscription(ctx context.Context, id int64) error {
	path := urlEscapePath("/subscriptions/{id}", strconv.FormatInt(id, 10))
	return doNoContent(c, ctx, "DELETE", path, nil, nil)
}

// GetSubscription Get a single subscription by ID.
//
// GET /subscriptions/{id}
func (c *Client) GetSubscription(ctx context.Context, id int64) (*Subscription, error) {
	path := urlEscapePath("/subscriptions/{id}", strconv.FormatInt(id, 10))
	return do[Subscription](c, ctx, "GET", path, nil, nil)
}

// UpdateSubscription Update a subscription.
//
// PUT /subscriptions/{id}
func (c *Client) UpdateSubscription(ctx context.Context, id int64, body UpdateSubscriptionRequest) (*Subscription, error) {
	path := urlEscapePath("/subscriptions/{id}", strconv.FormatInt(id, 10))
	return do[Subscription](c, ctx, "PUT", path, nil, body)
}

// ListDeliveries List delivery attempts for a subscription.
//
// GET /subscriptions/{id}/deliveries
func (c *Client) ListDeliveries(ctx context.Context, id int64, params ListDeliveriesParams) (*ListDeliveriesResponse, error) {
	path := urlEscapePath("/subscriptions/{id}/deliveries", strconv.FormatInt(id, 10))
	query := params.values()
	return do[ListDeliveriesResponse](c, ctx, "GET", path, query, nil)
}

// ListDeliveriesParams are the query parameters for ListDeliveries.
type ListDeliveriesParams struct {
	Limit    int64
	Envelope string
	Pretty   string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p ListDeliveriesParams) values() url.Values {
	v := url.Values{}
	if p.Limit != 0 {
		v.Set("limit", strconv.FormatInt(p.Limit, 10))
	}
	if p.Envelope != "" {
		v.Set("envelope", p.Envelope)
	}
	if p.Pretty != "" {
		v.Set("pretty", p.Pretty)
	}
	return v
}

// CurrentTenant Describe the calling tenant.
//
// GET /tenant
func (c *Client) CurrentTenant(ctx context.Context) (*CurrentTenant, error) {
	path := "/tenant"
	return do[CurrentTenant](c, ctx, "GET", path, nil, nil)
}

// CurrentTenantUsage Usage for the calling tenant.
//
// GET /tenant/usage
func (c *Client) CurrentTenantUsage(ctx context.Context, params CurrentTenantUsageParams) (*UsagePage, error) {
	path := "/tenant/usage"
	query := params.values()
	return do[UsagePage](c, ctx, "GET", path, query, nil)
}

// CurrentTenantUsageParams are the query parameters for CurrentTenantUsage.
type CurrentTenantUsageParams struct {
	Days   int64
	Pretty string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p CurrentTenantUsageParams) values() url.Values {
	v := url.Values{}
	if p.Days != 0 {
		v.Set("days", strconv.FormatInt(p.Days, 10))
	}
	if p.Pretty != "" {
		v.Set("pretty", p.Pretty)
	}
	return v
}

// TenantWatchList List the tenant's watched contracts.
//
// GET /tenant/watch
func (c *Client) TenantWatchList(ctx context.Context) (*TenantWatchList, error) {
	path := "/tenant/watch"
	return do[TenantWatchList](c, ctx, "GET", path, nil, nil)
}

// AddTenantWatch Add a contract to the tenant's watch list.
//
// POST /tenant/watch
func (c *Client) AddTenantWatch(ctx context.Context, body WatchedContractRequest) (*TenantWatchList, error) {
	path := "/tenant/watch"
	return do[TenantWatchList](c, ctx, "POST", path, nil, body)
}

// RemoveTenantWatch Remove a contract from the tenant's watch list.
//
// DELETE /tenant/watch/{contract_id}
func (c *Client) RemoveTenantWatch(ctx context.Context, contractID string) (*TenantWatchList, error) {
	path := urlEscapePath("/tenant/watch/{contract_id}", contractID)
	return do[TenantWatchList](c, ctx, "DELETE", path, nil, nil)
}

// Version Build version information.
//
// GET /version
func (c *Client) Version(ctx context.Context) (*VersionResponse, error) {
	path := "/version"
	return do[VersionResponse](c, ctx, "GET", path, nil, nil)
}

// ListWatchedContracts List watched contracts.
//
// GET /watched-contracts
func (c *Client) ListWatchedContracts(ctx context.Context) (*WatchedContractsPage, error) {
	path := "/watched-contracts"
	return do[WatchedContractsPage](c, ctx, "GET", path, nil, nil)
}

// AddWatchedContract Add a watched contract.
//
// POST /watched-contracts
func (c *Client) AddWatchedContract(ctx context.Context, params AddWatchedContractParams, body WatchedContractRequest) (*WatchedContractAdded, error) {
	path := "/watched-contracts"
	query := params.values()
	return do[WatchedContractAdded](c, ctx, "POST", path, query, body)
}

// AddWatchedContractParams are the query parameters for AddWatchedContract.
type AddWatchedContractParams struct {
	Confirm string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p AddWatchedContractParams) values() url.Values {
	v := url.Values{}
	if p.Confirm != "" {
		v.Set("confirm", p.Confirm)
	}
	return v
}

// RemoveWatchedContract Stop watching a contract.
//
// DELETE /watched-contracts/{id}
func (c *Client) RemoveWatchedContract(ctx context.Context, id string, params RemoveWatchedContractParams) (*WatchedContractRemoved, error) {
	path := urlEscapePath("/watched-contracts/{id}", id)
	query := params.values()
	return do[WatchedContractRemoved](c, ctx, "DELETE", path, query, nil)
}

// RemoveWatchedContractParams are the query parameters for RemoveWatchedContract.
type RemoveWatchedContractParams struct {
	Confirm string
}

// values renders the non-zero fields as query parameters, so an
// unset field is omitted from the URL rather than sent as empty.
func (p RemoveWatchedContractParams) values() url.Values {
	v := url.Values{}
	if p.Confirm != "" {
		v.Set("confirm", p.Confirm)
	}
	return v
}
